print("Eleazar")
print("listening to music")
print()
print("hello")
"Finished!"
print("    *  ")
print("   ***")
print(   "  *****" )
print( "      * ")
print( "   *     * ")
print( " * Eleazar * ")
print( "   *     * ")
print( "      *  ")
print( " I'm trying to learn python \n ")
print( " Hello World! " )
print("")
print( " Goodbye! " )
print("Hello")
print("Hello!")
print("Hi!")
print("Welcome")
print("Hello!")
print("Elazar" * 4 )
print( " Elazar " * 4 )
print( "Elazar \n " * 4 )
